DROP TABLE especialidad;

CREATE TABLE `especialidad` (
  `ID_ESPECIALIDAD` varchar(5) NOT NULL,
  `NOMBRE` varchar(35) NOT NULL,
  PRIMARY KEY (`ID_ESPECIALIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO especialidad VALUES("kine1","Kinesiologo");
INSERT INTO especialidad VALUES("odon1","Odontologo");



DROP TABLE medico;

CREATE TABLE `medico` (
  `ID_MEDICO` varchar(5) NOT NULL,
  `NOMBRE` varchar(25) NOT NULL,
  `TELEFONO` varchar(15) NOT NULL,
  `ID_ESPECIALIDAD` varchar(5) NOT NULL,
  PRIMARY KEY (`ID_MEDICO`),
  KEY `FK_MED_ESP` (`ID_ESPECIALIDAD`),
  CONSTRAINT `FK_MED_ESP` FOREIGN KEY (`ID_ESPECIALIDAD`) REFERENCES `especialidad` (`ID_ESPECIALIDAD`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO medico VALUES("med01","Pablo Torres","638493026","kine1");
INSERT INTO medico VALUES("med02","Samuel Uribe","430957481","odon1");



DROP TABLE paciente;

CREATE TABLE `paciente` (
  `ID_PACIENTE` varchar(5) NOT NULL,
  `NOMBRE` varchar(25) NOT NULL,
  `TELEFONO` varchar(15) NOT NULL,
  `CORREO` varchar(20) NOT NULL,
  PRIMARY KEY (`ID_PACIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO paciente VALUES("001","Marcelo Morin","987654321","marcelo@gmail.com");
INSERT INTO paciente VALUES("002","Zinedine Zidane","12356789","zzizou@gmail.com");



DROP TABLE reserva;

CREATE TABLE `reserva` (
  `ID_RESERVA` varchar(5) NOT NULL,
  `ID_PACIENTE` varchar(5) NOT NULL,
  `ID_MEDICO` varchar(5) NOT NULL,
  `ID_ESPECIALIDAD` varchar(5) NOT NULL,
  `HORA` time NOT NULL,
  `FECHA` date NOT NULL,
  PRIMARY KEY (`ID_RESERVA`),
  KEY `FK_RES_PAC` (`ID_PACIENTE`),
  KEY `FK_RES_MED` (`ID_MEDICO`),
  KEY `FK_RES_ESP` (`ID_ESPECIALIDAD`),
  CONSTRAINT `FK_RES_ESP` FOREIGN KEY (`ID_ESPECIALIDAD`) REFERENCES `especialidad` (`ID_ESPECIALIDAD`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_RES_MED` FOREIGN KEY (`ID_MEDICO`) REFERENCES `medico` (`ID_MEDICO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_RES_PAC` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `paciente` (`ID_PACIENTE`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO reserva VALUES("res01","001","med01","kine1","08:30:00","2019-08-08");
INSERT INTO reserva VALUES("res02","002","med02","odon1","10:00:00","2019-08-09");



